### ISSUE TITLE
options.baseDir does not seem to work

### ISSUE THREAD

**Issue by paazmaya** [ehynds/grunt-image-embed#22]
While setting up the options as described in the README, using the `baseDir` either relative path to the `Gruntfile.js` nor absolute path, does not seem to work.

In both of the cases, images with absolute paths in CSS are not found, as they are looked for in the `node_modules.....` path.

**Comment by joefiorini** [comment]
I'm seeing the same issue as @paazmaya. It appears the image function in `tasks/lib/encode.js` is getting the full path (`node_modules/grunt-image-embed/tasks/lib/<image.png>`) handed into it as the `img` parameter.

**Comment by joefiorini** [comment]
Figured it out. My `baseDir` was incorrect. It appears the path is relative to the path where you run Grunt, not the path were the task is configured.

**Comment by mspoerer** [comment]
+1

**Comment by nhoizey** [comment]
I can't make it work, never finds the image… :-/

**Comment by maurojs10** [comment]
It seems that `options.baseDir` works if you set it to a path relative to the CSS file specified with  `src`. And you must terminate it with  `/`.
Furthermore, the folder pointed by `options.baseDir` must contain the same subfolders used in the CSS. Example, if the CSS specifies `url("images/example.png")`, the folder must contain a subfolder named `images`.

**Comment by slacto** [comment]
This works
            imageEmbed: {
                dist: {
                    src: ['frontend/css/style.css'],
                    dest: 'frontend/css/style.css',
                    options: {
                        deleteAfterEncoding: false,
                        baseDir: './',
                        preEncodeCallback: function(filename) {
                            //console.log(filename);
                            return filename.indexOf('fonts') < 0;
                        }
                    }
                }
            }

**Comment by paazmaya** [comment]
Closing as "possibly out of date". Goodbye.
