### ISSUE TITLE
Task hangs when source files can't be found

### ISSUE THREAD

**Issue by RobbinHabermehl** [ehynds/grunt-image-embed#27]
I'm using version 0.3.1 of "grunt-image-embed" and configured the task as follows:

```
imageEmbed: {
    dev: {
        dest: 'app/css/',
        expand: true,
        flatten: true,
        src: 'app/css/**/*.css'
    }
}
```

In case no stylesheets are found based upon the "src" mapping, the task will run infinitely.

Just clear the CSS folder in order to reproduce this issue.

**Comment by vectart** [comment]
#36 looks like a fix

**Comment by ehynds** [comment]
yeah. fixed via #36

**Comment by vectart** [comment]
@ehynds Could I kindly ask you to deploy NPM package, so that we would fix our project build process?

**Comment by ehynds** [comment]
@vectart all set!

**Comment by vectart** [comment]
@ehynds thank you very much!
