### ISSUE TITLE
Fails encoding fonts (eot, woff, etc) - can filter for file types be added?

### ISSUE THREAD

**Issue by shubik** [ehynds/grunt-image-embed#33]
Is it possible to add an optional filter for accepted file types, e.g. ["gif", "jpg", "png"] which grunt-image-embed will try to encode? Because it fails for me trying to encode web fonts.

**Comment by wegorich** [comment]
Agree with you, have same trouble

**Comment by shubik** [comment]
I have fixed this in my private branch https://github.com/shubik/grunt-image-embed -- need to do a pull request

**Comment by shubik** [comment]
https://github.com/shubik/grunt-image-embed/blob/master/tasks/lib/encode.js#L50

**Comment by ehynds** [comment]
thanks @shubik!
